//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhillipKuhrt.VoTra.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhillipKuhrt.VoTra.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _1_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("_1_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1downarrow_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("_1downarrow_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1downarrow1_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("_1downarrow1_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1leftarrow_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("_1leftarrow_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1rightarrow_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("_1rightarrow_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1uparrow_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("_1uparrow_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("_2_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2downarrow_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("_2downarrow_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2leftarrow_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("_2leftarrow_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2rightarrow_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("_2rightarrow_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2uparrow_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("_2uparrow_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _3_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("_3_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _4_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("_4_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _5_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("_5_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Icons stammen von:
        ///
        ///-David Hopkins von SEM Labs; Creative Commons (by) Lizenz (http://semlabs.co.uk/cv).
        ///-David Vignoni; GNU LGPL 2.1 (http://www.icon-king.com/projects/nuvola/).
        ///-Everaldo Coelho and YellowIcon; GNU LGPL 2.1 (http://www.everaldo.com/crystal/).
        ///-IconBuffet (http://www.IconBuffet.com)
        ///-Wikimedia Commons; GNU LGPL 2.1 (http://commons.wikimedia.org)
        ///
        ///Bei der Suche sehr geholfen hat die Website http://www.iconspedia.com.
        ///
        ///
        ///Teile des Codes wurden übernommen von:
        ///
        ///-Matthias Hertel [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap agt_action_fail1_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("agt_action_fail1_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap agt_action_success_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("agt_action_success_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap agt_back_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("agt_back_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap agt_forward_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("agt_forward_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap agt_stop1_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("agt_stop1_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap agt_update_critical_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("agt_update_critical_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap attach_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("attach_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bell_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("bell_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bookmark_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("bookmark_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bookmark_add_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("bookmark_add_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bookmark_folder_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("bookmark_folder_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bookmark_toolbar_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("bookmark_toolbar_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bookmarks_list_add_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("bookmarks_list_add_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_cancel_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("button_cancel_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_ok_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("button_ok_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cnrdelete_all1_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("cnrdelete_all1_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap configure_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("configure_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap connect_creating_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("connect_creating_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap connect_established_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("connect_established_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap connect_no_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("connect_no_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap demo_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("demo_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_add_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("edit_add_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_remove_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("edit_remove_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap editclear_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("editclear_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap editcopy_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("editcopy_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap editcut_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("editcut_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap editpaste_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("editpaste_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edittrash_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("edittrash_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap endturn_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("endturn_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fileclose_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("fileclose_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filenew_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("filenew_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fileopen_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("fileopen_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fileprint_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("fileprint_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fileprint1_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("fileprint1_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filesave_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("filesave_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filesaveas_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("filesaveas_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filter_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("filter_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap find_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("find_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("folder_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_new_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("folder_new_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderClosed {
            get {
                object obj = ResourceManager.GetObject("FolderClosed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderOpen {
            get {
                object obj = ResourceManager.GetObject("FolderOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap funct_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("funct_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gohome_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("gohome_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Home {
            get {
                object obj = ResourceManager.GetObject("Home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap info_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("info_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kalarm_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("kalarm_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kalarm_disabled_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("kalarm_disabled_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap messagebox_critical_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("messagebox_critical_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap money_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("money_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap newfont_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("newfont_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PhillipKuhrtBig {
            get {
                object obj = ResourceManager.GetObject("PhillipKuhrtBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap player_time_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("player_time_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("search_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toggle_log_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("toggle_log_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Users {
            get {
                object obj = ResourceManager.GetObject("Users", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Users_Add {
            get {
                object obj = ResourceManager.GetObject("Users_Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Users_Edit {
            get {
                object obj = ResourceManager.GetObject("Users_Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Users_Go {
            get {
                object obj = ResourceManager.GetObject("Users_Go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Users_Remove {
            get {
                object obj = ResourceManager.GetObject("Users_Remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Users_Search {
            get {
                object obj = ResourceManager.GetObject("Users_Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_detailed_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("view_detailed_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_icon_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("view_icon_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_multicolumn_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("view_multicolumn_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wizard_256x256_32 {
            get {
                object obj = ResourceManager.GetObject("wizard_256x256_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
